package io.novafoundation.nova.feature_cloud_backup_api.domain.model.errors

class InvalidBackupPasswordError : Throwable(), CloudBackupWrongPassword
